micronaut:
  application:
    name: taskManager
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/taskmanager
    driverClassName: org.postgresql.Driver
    username: postgres
    password: secretpass
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
