micronaut:
  application:
    name: taskManager

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/taskmanager
    driverClassName: org.postgresql.Driver
    username: postgres
    password: secretpass
    schema-generate: CREATE_DROP
    dialect: POSTGRES

flyway:
  datasources:
    default:
      enabled: true

vertx:
  pg:
    client:
      port: 5432
      host: localhost
      database: taskmanager
      user: postgres
      password: secretpass
      maxSize: 5
